spring:
  application:
    name: chat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  codec:
    max-in-memory-size: 10MB
  data:
    mongodb:
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
