server:
  port: 0

spring:
  mongodb:
    uri: ${SPRING_MONGODB_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO
